inherit_gem:
  boxt_rubocop:
    - rspec.yml

inherit_mode:
  merge:
    - Exclude

require:
  - boxt_rubocop

plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - gemfiles/**/*
