inherit_gem:
  boxt_rubocop:
    - rspec.yml

inherit_mode:
  merge:
    - Exclude

require:
  - boxt_rubocop
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - gemfiles/**/*
