version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/ruby:2.7.2
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - restore_cache:
          keys:
            - kaminari-api-meta-data-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle Install
          command: bundle install
      - save_cache:
          key: kaminari-api-meta-data-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Run rubocop
          command: bundle exec rubocop
      - run:
          name: Run tests
          command: bundle exec rake test
      - store_test_results:
          path: test_results
